version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classgram
    ports:
      - "5432:5432"
    networks:
      - classgram

networks:
  classgram:
    driver: bridge